### ISSUE TITLE
The logic of generate action sequence

### ISSUE THREAD

**Issue by deepkun** [texttheater/geopar#9]
Hi, I'm trying to use your code for chinese semantic parsing. Do you hava any document for generating action sequence? I'm quite confused about the logic.

**Comment by deepkun** [comment]
When I parse two sentence with same meaning but different order, only one of them can generate orcale action sequence. 
![image](https://user-images.githubusercontent.com/87843659/131214178-efd9b5e3-103a-4308-8345-82b61fbda4c1.png)
![image](https://user-images.githubusercontent.com/87843659/131214203-2a816cb5-576c-4d2d-99bc-089cea86e695.png)
Is the action sequence highly correlated with the order?

**Comment by texttheater** [comment]
Hi, yes, this code is quite limited in that respect, it is just a simple teaching tool. I have some documentation in the lecture notes (https://kilian.evang.name/sp/lectures/intro.pdf) but it doesn't really go into action sequence generation, unfortunately.

**Comment by deepkun** [comment]
Thanks, the notes help a lot. Does your lecture have any online vedio？

**Comment by texttheater** [comment]
Unfortunately, there is no video.
